spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/jm_pormar_db?currentSchema=public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.jmpormar: INFO
